version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb-container
    env_file:
      - .env
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/backend
    container_name: backend-container
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
