version: '3.8'

services:
  mongo:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
    ports:
      - 27017:27017
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0
    volumes:
      - .:/backend
    container_name: backend-container
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 8000:8000
